def COLOR_MAP = [
    'SUCCESS': 'good',
    'FAILURE': 'danger'

]
pipeline {
    agent any
    tools {
        maven "MAVEN3.9.9"
        jdk "JDK17"
    }
    
    environment {
                CLUSTER_NAME = 'prod-cluster'
                SERVICE_NAME = 'vprofile-task-2-service-a2mllyzn'
       
    }

    stages {
        
            stage('Deploy to ECS') {
            steps {
                withAWS( credentials: 'awscred2', region: 'us-east-1' ) {
                    sh 'aws ecs update-service --cluster ${CLUSTER_NAME} --service ${SERVICE_NAME} --force-new-deployment'
                }
            }
        }

            
            
            
            post {
                always {
                    echo "Slack Notification"
                    slackSend channel: '#cicd',
                              color: COLOR_MAP[currentBuild.currentResult],
                              message: "*${currentBuild.currentResult}:* Job '${env.JOB_NAME}' build (${env.BUILD_NUMBER}) , \n more info at ${env.BUILD_URL} "
                }
            }
    }
}

