- name: Common tool setup on all the servers
  hosts: appsrvgrp
  become: yes

  tasks:


    - name: Install JDK on Ubuntu 
      apt:
        name: openjdk-17-jdk
        state: present
        update_cache: yes
      when: ansible_distribution == 'Ubuntu' 







    - name: Setup Tomcat systemd service file on Ubuntu 
      template:
        src: templates/ubuntu22-svcfile.j2
        dest: /etc/systemd/system/tomcat.service
        mode: '0644'
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version >= '16'

    - name: Reload tomcat svc config in ubuntu 14/15
      command: update-rc.d tomcat defaults
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version < '16'

    - name: Reload tomcat svc config in Centos 6
      command: chkconfig --add tomcat
      when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '6'

    - name: just force systemd to reread configs (2.4 and above)
      systemd:
        daemon_reload: yes 
      when: ansible_distribution_major_version > '6' or ansible_distribution_major_version > '15'



    - name: Start & Enable TOmcat 9
      service:
        name: tomcat
        state: started
        enabled: yes

   
